name: TrondUlseth
favicon: null
layout_spectrum: 0.87749
typography_spectrum: 0.03207329614087939
title: Trond Ulseth on the Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#4b100c'
    - '#a58248'
    - '#a82219'
    - '#d3aa6c'
  brandStrength: 0.940937043633312
  lightness: 0.6817958622705191
  saturation: 0.6697244218084961
  rhythmicContrast: 0.04781234357506037
purpose: []
