typography_spectrum: 0.46957545122131705
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.44066853472031653
  lightness: 0.20318895997479558
  saturation: 0.5654544052667916
  rhythmicContrast: 0.028279464691877365
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.07960827019996941
analytics:
  google: null
  facebook: null
  twitter: null
name: TrondUlseth
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Home
    id: bd202865-8ed1-4e8d-a581-47b633142173
    type: content
favicon: null
title: Trond Ulseth on the Grid
description: Testing codeless waters on the web
purpose: []
